name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions-rs/cargo@v1
      name: Linter 
      with:
        command: fmt
        args: --all -- --check
    
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: 1.82.0
        override: true
    
    - name: Build
      run: cargo build
    
    - name: Build
      run: cargo build --all-features

    - name: Run tests
      run: cargo test --all-features

    - name: Config documentation
      run: |
        cargo test generate_default_preset --all-features
        echo "Default Preset" >> $GITHUB_STEP_SUMMARY
        echo "==============" >> $GITHUB_STEP_SUMMARY
        python3 tools/jsonmd.py default.json >> $GITHUB_STEP_SUMMARY 
        rm default.json
        
  publish:
    name: Publish Library
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Publish
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login $TOKEN
          cargo publish
